package scalar.entity;

import java.util.ArrayList;



/**
 * Users generated by MyEclipse - Hibernate Tools
 */
public class Person  {

    // Constructors
	private String URI; //id/person-institution/number
	private String id;
	
	private String displayName; //name
	private String displayNameURI;
	
	
	private String mainRepresentationURI;//image

	private String birthURI;
	private String deathURI;
	private String birthPlace;
	private String deathPlace;
	private String birthDate;
	private String deathDate;
	
	private String nationalityURI;
	private String nationality;
	
	private String associateEventURI;
	private String associatePlace;
	private String artistBio;
	private String primaryArtistBio;
	
	private String dbpediaURI;
	private String nytimesURI;
	private String fbaseURI;
	private String wikipediaURI;

	private ArrayList<Work> collectionList;
	
    /** default constructor */
    public Person() {
    }


    public Person(String uri, String id, String displayName, String displayNameURI, String mainRepresentationURI, String birthURI, String deathURI, String birthPlace, String deathPlace, String birthDate, String deathDate, String nationalityURI, String nationality, String associateEventURI, String associatePlace,String artistBio, String primaryArtistBio, String dbpediaURI, String nytimesURI, String fbaseURI, String wikipediaURI,ArrayList<Work> collectionList) {
		super();
		this.URI = uri;
		this.id=id;
		this.displayName = displayName;
		this.displayNameURI = displayNameURI;
		this.mainRepresentationURI = mainRepresentationURI;
		this.birthURI = birthURI;
		this.deathURI = deathURI;
		this.birthPlace = birthPlace;
		this.deathPlace = deathPlace;
		this.birthDate = birthDate;
		this.deathDate = deathDate;
		this.nationalityURI = nationalityURI;
		this.nationality = nationality;
		this.associateEventURI = associateEventURI;
		this.associatePlace=associatePlace;
		this.artistBio = artistBio;
		this.primaryArtistBio = primaryArtistBio;
		this.dbpediaURI = dbpediaURI;
		this.nytimesURI = nytimesURI;
		this.wikipediaURI=wikipediaURI;
		this.fbaseURI = fbaseURI;
		
		this.collectionList=new ArrayList<Work>();
    	for(Work temp:collectionList)
    		this.collectionList.add(temp);
	}



	public String getArtistBio() {
		return artistBio;
	}


	public void setArtistBio(String artistBio) {
		this.artistBio = artistBio;
	}


	public String getAssociateEventURI() {
		return associateEventURI;
	}


	public void setAssociateEventURI(String associateEventURI) {
		this.associateEventURI = associateEventURI;
	}


	public String getBirthDate() {
		return birthDate;
	}


	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}


	public String getBirthPlace() {
		return birthPlace;
	}


	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}


	public String getBirthURI() {
		return birthURI;
	}


	public void setBirthURI(String birthURI) {
		this.birthURI = birthURI;
	}


	public ArrayList<Work> getCollectionList() {
		return collectionList;
	}


	public void setCollectionList(ArrayList<Work> collectionList) {
		this.collectionList=new ArrayList<Work>();
		for(Work temp:collectionList)
			this.collectionList.add(temp);
		}


	public String getDbpediaURI() {
		return dbpediaURI;
	}


	public void setDbpediaURI(String dbpediaURI) {
		this.dbpediaURI = dbpediaURI;
	}


	public String getDeathDate() {
		return deathDate;
	}


	public void setDeathDate(String deathDate) {
		this.deathDate = deathDate;
	}


	public String getDeathPlace() {
		return deathPlace;
	}


	public void setDeathPlace(String deathPlace) {
		this.deathPlace = deathPlace;
	}


	public String getDeathURI() {
		return deathURI;
	}


	public void setDeathURI(String deathURI) {
		this.deathURI = deathURI;
	}


	public String getDisplayName() {
		return displayName;
	}


	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}


	public String getDisplayNameURI() {
		return displayNameURI;
	}


	public void setDisplayNameURI(String displayNameURI) {
		this.displayNameURI = displayNameURI;
	}


	public String getFbaseURI() {
		return fbaseURI;
	}


	public void setFbaseURI(String fbaseURI) {
		this.fbaseURI = fbaseURI;
	}


	public String getMainRepresentationURI() {
		return mainRepresentationURI;
	}


	public void setMainRepresentationURI(String mainRepresentationURI) {
		this.mainRepresentationURI = mainRepresentationURI;
	}


	public String getNationality() {
		return nationality;
	}


	public void setNationality(String nationality) {
		this.nationality = nationality;
	}


	public String getNationalityURI() {
		return nationalityURI;
	}


	public void setNationalityURI(String nationalityURI) {
		this.nationalityURI = nationalityURI;
	}


	public String getNytimesURI() {
		return nytimesURI;
	}


	public void setNytimesURI(String nytimesURI) {
		this.nytimesURI = nytimesURI;
	}


	public String getPrimaryArtistBio() {
		return primaryArtistBio;
	}


	public void setPrimaryArtistBio(String primaryArtistBio) {
		this.primaryArtistBio = primaryArtistBio;
	}


	public String getURI() {
		return URI;
	}


	public void setURI(String uri) {
		URI = uri;
	}


	public String getAssociatePlace() {
		return associatePlace;
	}


	public void setAssociatePlace(String associatePlace) {
		this.associatePlace = associatePlace;
	}


	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public String getWikipediaURI() {
		return wikipediaURI;
	}


	public void setWikipediaURI(String wikipediaURI) {
		this.wikipediaURI = wikipediaURI;
	}


	

}
