package scalar.entity;

import java.util.ArrayList;
// Generated by MyEclipse - Hibernate Tools



/**
 * Users generated by MyEclipse - Hibernate Tools
 */
public class Work  {

    // Constructors
	private String URI;
	
	private String representationURI;
	
	private String idURI;
	private String id;
	private String titleURI;
	private String title;
	
	private String acquisitionURI;
	
	private String objnumURI;
	private String objnum;
	
	private String keeperURI;
	private String keeper;
	
	private String description;
	
	private String mainClassURI;
	private String mainClass;
	
	private String subClassURI;
	private String subClass;
	
	private String locationURI;
	private String location;
	
    private ArrayList<String> keywordURIList;
    private ArrayList<String> keywordList;
    
    private String dimensionURI;
    private String width;
    private String height;
    
    private ArrayList<Person> personList;
    
    /** default constructor */
    public Work() {
    }

    
    
    public Work(String uri, String representationURI, String idURI, String id, String titleURI, String title, String acquisitionURI, String objnumURI, String objnum, String keeperURI, String keeper, String description, String mainClassURI, String mainClass, String subClassURI, String subClass, String locationURI, String location, ArrayList<String> keywordURIList, ArrayList<String> keywordList, String dimensionURI, String width, String height, ArrayList<Person> personList) {
		super();
		URI = uri;
		this.representationURI = representationURI;
		this.idURI = idURI;
		this.id = id;
		this.titleURI = titleURI;
		this.title = title;
		this.acquisitionURI = acquisitionURI;
		this.objnumURI = objnumURI;
		this.objnum = objnum;
		this.keeperURI = keeperURI;
		this.keeper = keeper;
		this.description = description;
		this.mainClassURI = mainClassURI;
		this.mainClass = mainClass;
		this.subClassURI = subClassURI;
		this.subClass = subClass;
		this.locationURI = locationURI;
		this.location = location;
		this.keywordURIList = keywordURIList;
		this.keywordList = keywordList;
		this.dimensionURI = dimensionURI;
		this.width = width;
		this.height = height;
		this.personList = personList;
	}



	/** full constructor */
    public Work(String userName, String password) {
        
    }



	public String getAcquisitionURI() {
		return acquisitionURI;
	}



	public void setAcquisitionURI(String acquisitionURI) {
		this.acquisitionURI = acquisitionURI;
	}



	public String getDescription() {
		return description;
	}



	public void setDescription(String description) {
		this.description = description;
	}



	public String getDimensionURI() {
		return dimensionURI;
	}



	public void setDimensionURI(String dimensionURI) {
		this.dimensionURI = dimensionURI;
	}



	public String getHeight() {
		return height;
	}



	public void setHeight(String height) {
		this.height = height;
	}



	public String getId() {
		return id;
	}



	public void setId(String id) {
		this.id = id;
	}



	public String getIdURI() {
		return idURI;
	}



	public void setIdURI(String idURI) {
		this.idURI = idURI;
	}



	public String getKeeper() {
		return keeper;
	}



	public void setKeeper(String keeper) {
		this.keeper = keeper;
	}



	public String getKeeperURI() {
		return keeperURI;
	}



	public void setKeeperURI(String keeperURI) {
		this.keeperURI = keeperURI;
	}



	public ArrayList<String> getKeywordList() {
		return keywordList;
	}



	public void setKeywordList(ArrayList<String> keywordList) {
		this.keywordList = keywordList;
	}



	public ArrayList<String> getKeywordURIList() {
		return keywordURIList;
	}



	public void setKeywordURIList(ArrayList<String> keywordURIList) {
		this.keywordURIList = keywordURIList;
	}



	public String getLocation() {
		return location;
	}



	public void setLocation(String location) {
		this.location = location;
	}



	public String getLocationURI() {
		return locationURI;
	}



	public void setLocationURI(String locationURI) {
		this.locationURI = locationURI;
	}



	public String getMainClass() {
		return mainClass;
	}



	public void setMainClass(String mainClass) {
		this.mainClass = mainClass;
	}



	public String getMainClassURI() {
		return mainClassURI;
	}



	public void setMainClassURI(String mainClassURI) {
		this.mainClassURI = mainClassURI;
	}



	public String getObjnum() {
		return objnum;
	}



	public void setObjnum(String objnum) {
		this.objnum = objnum;
	}



	public String getObjnumURI() {
		return objnumURI;
	}



	public void setObjnumURI(String objnumURI) {
		this.objnumURI = objnumURI;
	}



	public ArrayList<Person> getPersonList() {
		return personList;
	}



	public void setPersonList(ArrayList<Person> personList) {
		this.personList = personList;
	}



	public String getRepresentationURI() {
		return representationURI;
	}



	public void setRepresentationURI(String representationURI) {
		this.representationURI = representationURI;
	}



	public String getSubClass() {
		return subClass;
	}



	public void setSubClass(String subClass) {
		this.subClass = subClass;
	}



	public String getSubClassURI() {
		return subClassURI;
	}



	public void setSubClassURI(String subClassURI) {
		this.subClassURI = subClassURI;
	}



	public String getTitle() {
		return title;
	}



	public void setTitle(String title) {
		this.title = title;
	}



	public String getTitleURI() {
		return titleURI;
	}



	public void setTitleURI(String titleURI) {
		this.titleURI = titleURI;
	}



	public String getURI() {
		return URI;
	}



	public void setURI(String uri) {
		URI = uri;
	}



	public String getWidth() {
		return width;
	}



	public void setWidth(String width) {
		this.width = width;
	}
    
    public void addKeywordURI(String uri)
    {
    	if( keywordURIList==null)
    		keywordURIList=new ArrayList<String>();
    	keywordURIList.add(uri);
    }
    
    public void addKeyword(String keyword)
    {
    	if (keywordList==null)
    		keywordList=new ArrayList<String>();
    	keywordList.add(keyword);
    }
   
}
